// <auto-generated />
using CouponDistribution.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CouponDistribution.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191209133851_BuildDatabase")]
    partial class BuildDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("CouponDistribution.DataModel.CouponOfCustomer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("Username");

                    b.ToTable("CouponsOfCustomer");
                });

            modelBuilder.Entity("CouponDistribution.DataModel.CouponOfSaler", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("Left")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("Name");

                    b.HasIndex("Username");

                    b.ToTable("CouponsOfSaler");
                });

            modelBuilder.Entity("CouponDistribution.DataModel.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnName("Username")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("Authorization")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasColumnName("Kind")
                        .HasColumnType("TEXT")
                        .HasMaxLength(8);

                    b.Property<string>("Password")
                        .HasColumnName("Password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CouponDistribution.DataModel.CouponOfCustomer", b =>
                {
                    b.HasOne("CouponDistribution.DataModel.User", "User")
                        .WithMany()
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CouponDistribution.DataModel.CouponOfSaler", b =>
                {
                    b.HasOne("CouponDistribution.DataModel.User", "User")
                        .WithMany()
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
