// <auto-generated />
using CouponDistribution.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CouponDistribution.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("CouponDistribution.DataModel.Coupon", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("left")
                        .HasColumnType("INTEGER");

                    b.Property<int>("stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("name");

                    b.HasIndex("username");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("CouponDistribution.DataModel.Coupon2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<string>("name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("username");

                    b.ToTable("Coupons2");
                });

            modelBuilder.Entity("CouponDistribution.DataModel.User", b =>
                {
                    b.Property<string>("username")
                        .HasColumnName("username")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("auth")
                        .HasColumnType("TEXT");

                    b.Property<string>("kind")
                        .HasColumnName("kind")
                        .HasColumnType("TEXT")
                        .HasMaxLength(8);

                    b.Property<string>("password")
                        .HasColumnName("password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.HasKey("username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CouponDistribution.DataModel.Coupon", b =>
                {
                    b.HasOne("CouponDistribution.DataModel.User", "User")
                        .WithMany()
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CouponDistribution.DataModel.Coupon2", b =>
                {
                    b.HasOne("CouponDistribution.DataModel.User", "User")
                        .WithMany()
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
